package com.skyline.sdc_project.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Player {
    @Id
    private int id;
    private String email;
    private String username;
    private String password;
    private String type;

    // Getters and setters are generated by Lombok, no need to define them manually
}